# Generated by Django 4.2.6 on 2023-12-03 08:56

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=12)),
                ('operator_code', models.CharField(max_length=10)),
                ('tag', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('message_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField()),
                ('sending_status', models.CharField(max_length=50)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDG.client')),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SDG.mailing')),
            ],
        ),
    ]
